
player = new Player(230,230,0.001,4.71,390,60);

gate = new Array();
gate[0] = new Gate(X_POSITION_GATE_1,Y_POSITION_GATE_1,HEALTH_GATE);
gate[1] = new Gate(X_POSITION_GATE_2,Y_POSITION_GATE_2,HEALTH_GATE);
gate[2] = new Gate(X_POSITION_GATE_3,Y_POSITION_GATE_3,HEALTH_GATE);
gate[3] = new Gate(X_POSITION_GATE_4,Y_POSITION_GATE_4,HEALTH_GATE);
