

player = new Player(AMPLITUDE_X, AMPLITUDE_Y, CIRCLE_SPEED, MOVEMENT_START_POSITION, PLAYER_STARTING_X, PLAYER_STARTING_Y);

gate = new Array();
gate[0] = new Gate(X_POSITION_GATE_1, Y_POSITION_GATE_1, HEALTH_GATE);
gate[1] = new Gate(X_POSITION_GATE_2, Y_POSITION_GATE_2, HEALTH_GATE);
gate[2] = new Gate(X_POSITION_GATE_3, Y_POSITION_GATE_3, HEALTH_GATE);
gate[3] = new Gate(X_POSITION_GATE_4, Y_POSITION_GATE_4, HEALTH_GATE);
